;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --dce -tnh -all -S -o - | filecheck %s

(module
  ;; CHECK:      (tag $tag (param i32))
  (tag $tag (param i32))

  ;; CHECK:      (func $block-in-if-arm
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:   (block
  ;; CHECK-NEXT:    (local.set $x
  ;; CHECK-NEXT:     (i32.const 1)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (local.set $x
  ;; CHECK-NEXT:     (i32.const 2)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (i32.const -1)
  ;; CHECK-NEXT:     (return)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $block-in-if-arm
    (local $x i32)
    (if
      (i32.const 1)
      (block
        ;; The unreachable later can be assumed to never be reached in tnh mode,
        ;; so we can remove code that is right before it. Specifically that
        ;; includes the sets of 3 and 4, but not 1 and 2, since they might not
        ;; get there if the return happens. (The sets of 5 and 6 can also be
        ;; removed, even in non-tnh mode.)
        (local.set $x
          (i32.const 1)
        )
        (local.set $x
          (i32.const 2)
        )
        (if
          (i32.const -1)
          (return)
        )
        (local.set $x
          (i32.const 3)
        )
        (local.set $x
          (i32.const 4)
        )
        (unreachable)
        (local.set $x
          (i32.const 5)
        )
        (local.set $x
          (i32.const 6)
        )
      )
    )
  )

  ;; CHECK:      (func $toplevel
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.const -1)
  ;; CHECK-NEXT:   (return)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $toplevel
    (local $x i32)
    ;; As above but at the toplevel.
    (local.set $x
      (i32.const 1)
    )
    (local.set $x
      (i32.const 2)
    )
    (if
      (i32.const -1)
      (return)
    )
    (local.set $x
      (i32.const 3)
    )
    (local.set $x
      (i32.const 4)
    )
    (unreachable)
    (local.set $x
      (i32.const 5)
    )
    (local.set $x
      (i32.const 6)
    )
  )

  ;; CHECK:      (func $middle
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.const -1)
  ;; CHECK-NEXT:   (return)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $middle
    (local $x i32)
    (local.set $x
      (i32.const 1)
    )
    (local.set $x
      (i32.const 2)
    )
    (if
      (i32.const -1)
      (return)
    )
    (local.set $x
      (i32.const 3)
    )
    (local.set $x
      (i32.const 4)
    )
    ;; The unreachable occurs in the middle of an expression here, not at the
    ;; top level of a block. But we'll optimize it to the top level first, so
    ;; we'll optimize just as fully here as before.
    (drop
      (i32.eqz
        (unreachable)
      )
    )
    (local.set $x
      (i32.const 5)
    )
    (local.set $x
      (i32.const 6)
    )
  )

  ;; CHECK:      (func $eh-pop
  ;; CHECK-NEXT:  (try $try
  ;; CHECK-NEXT:   (do
  ;; CHECK-NEXT:    (nop)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (catch $tag
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (pop i32)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $eh-pop
    (try
      (do
        (nop)
      )
      (catch $tag
        ;; We can dce out the nop, but not the pop - the pop is necessary for
        ;; validation.
        (drop
          (pop i32)
        )
        (nop)
        (unreachable)
      )
    )
  )
)
