;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: foreach %s %t wasm-opt -all --dae -S -o - | filecheck %s

(module
  (type $A (struct (field i32) (field i32)))

  (func $test
    (drop
      (struct.new $A
        (i32.const 10)
        (i32.const 10)
      )
    )
    (drop
      (struct.get $A 0
        (ref.null $A)
      )
    )
    (drop
      (struct.get $A 1
        (ref.null $A)
      )
    )
  )
)
