;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt --global-vacuum -all -S -o - | filecheck %s

(module
  ;; CHECK:      (type $none_=>_none (func))

  ;; CHECK:      (func $foo
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (call $unreachable)
  ;; CHECK-NEXT:  (call $call-nop)
  ;; CHECK-NEXT:  (call $call-unreachable)
  ;; CHECK-NEXT: )
  (func $foo
    ;; Calling a function with no effects can be optimized away.
    (call $nop)
    ;; Calling a function with effects cannot.
    (call $unreachable)
    ;; Calling a function with a loop cannot (the loop might hang forever, and
    ;; must stay that way).
    (call $loop)
    ;; Calling something that calls something with no effects can be optimized
    ;; away.
    (call $call-nop)
    ;; Calling something that calls something with effects cannot.
    (call $call-unreachable)
  )

  ;; CHECK:      (func $cycle
  ;; CHECK-NEXT:  (call $cycle)
  ;; CHECK-NEXT: )
  (func $cycle
    ;; Calling a function with no effects in a cycle cannot be optimized out -
    ;; this must keep hanging forever.
    (call $cycle)
  )

  ;; CHECK:      (func $nop
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $nop
    (nop)
  )

  ;; CHECK:      (func $unreachable
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $unreachable
    (unreachable)
  )

  (func $loop
    (loop)
  )

  ;; CHECK:      (func $call-nop
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $call-nop
    (call $nop)
  )

  ;; CHECK:      (func $call-unreachable
  ;; CHECK-NEXT:  (call $unreachable)
  ;; CHECK-NEXT: )
  (func $call-unreachable
    (call $unreachable)
  )
)
