;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --merge-locals -all -S -o - \
;; RUN:   | filecheck %s

(module
  (func $subtype-to-copy
    (local $0 anyref)
    (local $1 funcref)
    (local $2 funcref)
    (local.set $0
      (local.get $1)
    )
    ;; Test that merge-locals support subtyping. This get should be switched
    ;; to use $0.
    (drop
      (local.get $0)
    )
    (drop
      (local.get $1)
    )
  )

  (func $subtype-test (param $param i32)
    (local $0 anyref)
    (local $1 funcref)
    (local $2 funcref)
    (local.set $0
      (local.get $1)
    )
    ;; Another possible set exists, which 
    (if
      (local.get $param)
      (local.set $1
        (ref.null func)
      )
    )
    (drop
      (local.get $0)
    )
    (drop
      (local.get $1)
    )
  )
)

