;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --nominal --monomorphize-always -S -o - | filecheck %s

(module
  (import "a" "b" (global $g i32))

  (func $foo (param $x i32)
    (call $bar
      (i32.const 10)
    )
    (call $bar
      (i32.const 20)
    )
    ;; This cannot be monomorphized, as it is not a constant.
    (call $bar
      (local.get $x)
    )
    ;; But an immutable global can.
    (call $bar
      (global.get $g)
    )
  )

  (func $bar (param $x i32)
    (drop
      (local.get $x)
    )
  )
)
