;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.

;; RUN: wasm-opt %s --pack-strings=str.const,%s.json,%t -all -S -o - | filecheck %s

;; RUN: cat %t.wast | filecheck %s --check-prefix=OUTPUT

(module
  (import "str.const" "0" (global $hello (ref extern)))
  (import "str.const" "1" (global $world (ref extern)))
  (import "str.const" "3" (global $later (ref extern)))
  (import "str.const" "5" (global $bye (ref extern)))

  ;; A different module name. This is not modified.
  (import "string.const" "2" (global $other (ref extern)))
)
