;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --traps-never-happen --fuzz-exec -all -S -o - \
;; RUN:   | filecheck %s
;; RUN: wasm-opt %s --remove-unused-names --precompute-propagate --fuzz-exec -all --nominal -S -o - \
;; RUN:   | filecheck %s --check-prefix=NOMNL

(module
  (func $non-nullable (param $x (ref any))
    (local.set $x
      (ref.as_non_null
        (ref.null any)
      )
    )
  )

  (func $nullable (param $x (ref null any))
    (local.set $x
      (ref.as_non_null
        (ref.null any)
      )
    )
  )
)
