;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_test.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --nominal --unify-itable -all -S -o - | filecheck %s

(module
  ;; CHECK:      (type $none_=>_none (func_subtype func))

  ;; CHECK:      (type $vtable-1 (struct_subtype (field funcref) data))

  ;; CHECK:      (type $vtable-2 (struct_subtype (field funcref) (field funcref) data))

  ;; CHECK:      (type $vtable-3 (struct_subtype (field funcref) (field funcref) (field funcref) data))

  ;; CHECK:      (type $itable (array_subtype (mut (ref null data)) data))
  (type $itable (array (mut (ref null data))))

  (type $vtable-1 (struct (field funcref)))
  (type $vtable-2 (struct (field funcref) (field funcref)))
  (type $vtable-3 (struct (field funcref) (field funcref) (field funcref)))

  ;; CHECK:      (global $itable-1 (ref $itable) (array.init_static $itable
  ;; CHECK-NEXT:  (ref.null data)
  ;; CHECK-NEXT:  (struct.new $vtable-1
  ;; CHECK-NEXT:   (ref.func $a)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (struct.new $vtable-2
  ;; CHECK-NEXT:   (ref.func $b)
  ;; CHECK-NEXT:   (ref.func $c)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (ref.null data)
  ;; CHECK-NEXT:  (struct.new $vtable-3
  ;; CHECK-NEXT:   (ref.func $d)
  ;; CHECK-NEXT:   (ref.func $e)
  ;; CHECK-NEXT:   (ref.func $f)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: ))
  (global $itable-1 (ref $itable) (array.init_static $itable
    (ref.null data)
    (struct.new $vtable-1
      (ref.func $a)
    )
    (struct.new $vtable-2
      (ref.func $b)
      (ref.func $c)
    )
    (ref.null data)
    (struct.new $vtable-3
      (ref.func $d)
      (ref.func $e)
      (ref.func $f)
    )
  ))

  ;; CHECK:      (table $unified-table 6 6 funcref)

  ;; CHECK:      (elem (i32.const 0) $a $b $c $d $e $f)

  ;; CHECK:      (func $a
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $a)
  ;; CHECK:      (func $b
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $b)
  ;; CHECK:      (func $c
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $c)
  ;; CHECK:      (func $d
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $d)
  ;; CHECK:      (func $e
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $e)
  ;; CHECK:      (func $f
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $f)
)
