;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt --unsubtyping -all -S -o - | filecheck %s

(module
  (type $A (struct))
  (type $B (sub $A (struct (field i32))))

  (func $func
    (local $a (ref null $A))
    (local $b (ref null $B))
    (local.set $a
      (struct.new $A)
    )
    (local.set $b
      (struct.new $B)
    )
  )
)
