;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt --unsubtyping -all -S -o - | filecheck %s

(module
  (type $A (struct))
  (type $B (sub $A (struct (field i32))))

  (func $A (result (ref $A))
    (struct.new $A)
  )

  (func $B-A (result (ref $A))
    (struct.new $B)
  )
)
